version: '2.1'

services:
  wordpress:
    build: .
    ports:
      - '80:8080'
    volumes:
      - 'wordpress_data:/bitnami/wordpress'
    restart: always
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - WORDPRESS_DATABASE_USER=wp
      - WORDPRESS_DATABASE_NAME=wp
